server:
  port: 5002
eureka:
  #donde esta ubicado nuestro servicio eureka para registrarse y descubrimiento
  client:
    service-url.defaultZone: http://localhost:8300/eureka
    
  #creando una intancia randon en eureka por cada instancia levantada
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}   
spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: account-manager
      username: wspereira
      password: "Wspereira2022$"
      authentication-database: admin
  kafka:
    listener:
      ack-mode: MANUAL_IMMEDIATE
    consumer:
      bootstrap-servers: localhost:9092
      group-id: account-manager
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
  