server:
  port: 5003
eureka:
  #donde esta ubicado nuestro servicio eureka para registrarse y descubrimiento
  client:
    service-url.defaultZone: http://localhost:8300/eureka
    
  #creando una intancia randon en eureka por cada instancia levantada
  instance.instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}   
spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3308/movements-manager?createDatabaseIfNotExist=true
    username: "root"
    password: "wspereira_123$"
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer